In [ ]:
import torch

In [4]:
x = torch.IntTensor(5, 3)
print(x)


 0.0000e+00  1.6106e+09  1.9375e+09
 1.8791e+09  9.3612e+08  3.2759e+04
 9.3613e+08  3.2759e+04  9.3613e+08
 3.2759e+04  1.8699e+09  3.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.IntTensor of size 5x3]



In [5]:
x = torch.rand(5, 3)
print(x)


 0.9460  0.5461  0.3223
 0.2263  0.0959  0.8040
 0.9942  0.7669  0.4389
 0.1109  0.8945  0.4551
 0.0086  0.0879  0.1860
[torch.FloatTensor of size 5x3]



In [6]:
print(x.size())

torch.Size([5, 3])


In [7]:
y = torch.rand(5 ,3)
print(x + y)


 1.0691  0.8447  1.2095
 0.2472  0.4779  1.6573
 1.0830  1.5784  1.0445
 0.6579  1.0483  1.2160
 0.2351  0.6893  0.2835
[torch.FloatTensor of size 5x3]



In [10]:
print(torch.add(x, y))


 1.0691  0.8447  1.2095
 0.2472  0.4779  1.6573
 1.0830  1.5784  1.0445
 0.6579  1.0483  1.2160
 0.2351  0.6893  0.2835
[torch.FloatTensor of size 5x3]



In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.0691  0.8447  1.2095
 0.2472  0.4779  1.6573
 1.0830  1.5784  1.0445
 0.6579  1.0483  1.2160
 0.2351  0.6893  0.2835
[torch.FloatTensor of size 5x3]



In [14]:
y.add_(x)
print(y)


 1.0691  0.8447  1.2095
 0.2472  0.4779  1.6573
 1.0830  1.5784  1.0445
 0.6579  1.0483  1.2160
 0.2351  0.6893  0.2835
[torch.FloatTensor of size 5x3]



In [15]:
print(x[:, 1])


 0.5461
 0.0959
 0.7669
 0.8945
 0.0879
[torch.FloatTensor of size 5]



In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [22]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [24]:
a.add_(1)
print(a)
print(b)


 3
 3
 3
 3
 3
[torch.FloatTensor of size 5]

[ 3.  3.  3.  3.  3.]


In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [ ]:
print(torch.cuda.is_available())